name: Build and Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: "Create '.env.local' file"
              run: |
                echo "PORT=${{ secrets.PORT }}" >> .env.local
                echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
                echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env.local
                echo "WEB_URL=${{ secrets.WEB_URL }}" >> .env.local
                echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env.local
                echo "AUTH_FACEBOOK_ID=${{ secrets.AUTH_FACEBOOK_ID }}" >> .env.local
                echo "AUTH_FACEBOOK_SECRET=${{ secrets.AUTH_FACEBOOK_SECRET }}" >> .env.local
                echo "AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}" >> .env.local
                echo "AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}" >> .env.local
                echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> .env.local
                echo "ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}" >> .env.local
                echo "GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}" >> .env.local
                echo "GOOGLE_PRIVATE_KEY=\"${{ secrets.GOOGLE_PRIVATE_KEY }}\"" >> .env.local
            - name: build image
              run: docker build -t buithiendev/guyu:latest .
            - name: Log in to Docker Hub
              run: docker login -u ${{ secrets.USER_NAME_DOCKER_HUB }} -p ${{ secrets.ACCESS_TOKEN_DOCKER_HUB }}
            - name: Push Docker image to Docker Hub
              run: docker push buithiendev/guyu:latest
            - name: Log out of Docker Hub
              run: docker logout
            - name: "Remove '.env.production' file"
              run: rm -f .env.production
